# Request
geometry_msgs/Point[] point_list
---
# Result
geometry_msgs/Point[] point_list
uuv_interfaces/Samplevalue[] samples
---
# Feedback
string info
geometry_msgs/Point point
uuv_interfaces/Samplevalue samples